/**
 * Slot config - multi-slot configuration with Sales Team HQ, Customer Items, and Brand Item views
 */
export const defaultDataTableConfig = {
  dataSource: 'Primary',
  selectedQueryKey: 'primary',
  isAdminMode: true,
  enableReport: true,
  showChart: false,
  breakdownType: 'month',
  dateColumn: 'posting_date',
  columnGroupBy: 'values',
  slots: {
    salesTeamHq: {
      name: 'Sales Team HQ',
      enableSort: true,
      enableFilter: true,
      enableSummation: true,
      textFilterColumns: [],
      percentageColumns: [
        { columnName: 'Target %', valueField: 'inc_primary', targetField: 'target', beforeColumn: 'target' },
        { columnName: 'Prod %', valueField: 'prod_offer', targetField: 'target', beforeColumn: 'prod_offer' },
        { columnName: 'Inv %', valueField: 'inv_offer', targetField: 'target', beforeColumn: 'inv_offer' },
      ],
      derivedColumns: [],
      groupFields: ['sales_team', 'hq', 'customer_name'],
      allowedColumns: {
        main: [
          'sales_team',
          'target',
          'inc_primary',
          'gross_primary',
          'net_primary',
          'credit_note',
          'EXPIRED',
          'SALES_RETURN',
          'BREAKAGE',
          'CLAIM',
          'prod_offer',
          'inv_offer',
        ],
        report: [
          'sales_team',
          'hq',
          'customer_name',
          'target',
          'inc_primary',
          'gross_primary',
          'net_primary',
          'credit_note',
          'EXPIRED',
          'SALES_RETURN',
          'BREAKAGE',
          'CLAIM',
          'prod_offer',
          'inv_offer',
        ],
        group: {
          hq: [
            'hq',
            'target',
            'inc_primary',
            'gross_primary',
            'net_primary',
            'credit_note',
            'EXPIRED',
            'SALES_RETURN',
            'BREAKAGE',
            'CLAIM',
            'prod_offer',
            'inv_offer',
          ],
          customer_name: [
            'customer_name',
            'inc_primary',
            'gross_primary',
            'net_primary',
            'credit_note',
            'EXPIRED',
            'SALES_RETURN',
            'BREAKAGE',
            'CLAIM',
            'prod_offer',
            'inv_offer',
          ],
        },
      },
      redFields: [],
      greenFields: [],
      enableCellEdit: false,
      editableColumns: { main: [], nested: {} },
      drawerTabs: [
        { id: 'salesTeamHq-tab-1', name: 'Customer', outerGroup: 'customer_name', innerGroup: 'invoice' },
        { id: 'salesTeamHq-tab-2', name: 'Invoice', outerGroup: 'invoice', innerGroup: 'item_name' },
      ],
    },
    customerItems: {
      name: 'Customer Items',
      enableSort: true,
      enableFilter: true,
      enableSummation: true,
      textFilterColumns: [],
      percentageColumns: [],
      derivedColumns: [],
      groupFields: ['customer_name', 'item_name'],
      allowedColumns: {
        main: [
          'customer_name',
          'inc_primary',
          'gross_primary',
          'net_primary',
          'credit_note',
          'EXPIRED',
          'SALES_RETURN',
          'BREAKAGE',
          'CLAIM',
          'prod_offer',
          'inv_offer',
        ],
        report: [
          'customer_name',
          'inc_primary',
          'gross_primary',
          'net_primary',
          'credit_note',
          'EXPIRED',
          'SALES_RETURN',
          'BREAKAGE',
          'CLAIM',
          'prod_offer',
          'inv_offer',
        ],
        group: {
          item_name: [
            'item_name',
            'inc_primary',
            'gross_primary',
            'net_primary',
            'credit_note',
            'EXPIRED',
            'SALES_RETURN',
            'BREAKAGE',
            'CLAIM',
            'prod_offer',
            'inv_offer',
          ],
        },
      },
      redFields: [],
      greenFields: [],
      enableCellEdit: false,
      editableColumns: { main: [], nested: {} },
      drawerTabs: [],
    },
    BrandItem: {
      name: 'Brand Item',
      enableSort: true,
      enableFilter: true,
      enableSummation: true,
      textFilterColumns: [],
      percentageColumns: [],
      derivedColumns: [],
      groupFields: ['brand', 'item_name'],
      allowedColumns: {
        main: [
          'brand',
          'inc_primary',
          'gross_primary',
          'net_primary',
          'credit_note',
          'EXPIRED',
          'SALES_RETURN',
          'BREAKAGE',
          'CLAIM',
          'prod_offer',
          'inv_offer',
        ],
        report: [
          'brand',
          'item_name',
          'inc_primary',
          'gross_primary',
          'net_primary',
          'credit_note',
          'EXPIRED',
          'SALES_RETURN',
          'BREAKAGE',
          'CLAIM',
          'prod_offer',
          'inv_offer',
        ],
        group: {
          item_name: [
            'item_name',
            'inc_primary',
            'gross_primary',
            'net_primary',
            'credit_note',
            'EXPIRED',
            'SALES_RETURN',
            'BREAKAGE',
            'CLAIM',
            'prod_offer',
            'inv_offer',
          ],
        },
      },
      redFields: [],
      greenFields: [],
      enableCellEdit: false,
      editableColumns: { main: [], nested: {} },
      drawerTabs: [
        { id: 'BrandItem-tab-1', name: 'Team', outerGroup: 'customer_name', innerGroup: null },
        { id: 'BrandItem-tab-2', name: 'HQ', outerGroup: 'hq', innerGroup: null },
      ],
    },
  },
};
